//
//  CreateOrderWorker.swift
//  ClearStore
//
//  Created by Lucio Pham on 11/13/17.
//  Copyright (c) 2017 Lucio Pham. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CreateOrderWorker
{
  func doSomeWork()
  {
  }
}
