//
//  CreateOrderInteractor.swift
//  ClearStore
//
//  Created by Lucio Pham on 11/13/17.
//  Copyright (c) 2017 Lucio Pham. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateOrderBusinessLogic
{
  var shippingMethods: [String] { get }
  func formatExpirationDate(request:
    CreateOrder.FormatExpirationDate.Request)
}

protocol CreateOrderDataStore
{
  //var name: String { get set }
}

class CreateOrderInteractor: CreateOrderBusinessLogic, CreateOrderDataStore
{
  
  var presenter: CreateOrderPresentationLogic?
  var worker: CreateOrderWorker?
  
  var shippingMethods: [String] = ["Standar Shipping", "Two-day Shipping", "One-Day Shipping"]
  
  //From output of ViewController - Input for Interactor ** Output of Interactor - Input of Presenter
  func formatExpirationDate(request: CreateOrder.FormatExpirationDate.Request) {
    let response = CreateOrder.FormatExpirationDate.Response(date: request.date)
    presenter?.presentExpirationDate(response: response)
  }
}
