//
//  CreateOrderPresenter.swift
//  ClearStore
//
//  Created by Lucio Pham on 11/13/17.
//  Copyright (c) 2017 Lucio Pham. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateOrderPresentationLogic
{
  func presentExpirationDate(response: CreateOrder.FormatExpirationDate.Response)
}

class CreateOrderPresenter: CreateOrderPresentationLogic
{
  
  weak var viewController: CreateOrderDisplayLogic?
  
  let dateFormatter: DateFormatter = {
    let dateFormatter = DateFormatter()
    dateFormatter.dateStyle = .short
    dateFormatter.timeZone = .none
    return dateFormatter
  }()
  
  //From output of Interactor - Output of Presentor - Input of ViewController
  func presentExpirationDate(response: CreateOrder.FormatExpirationDate.Response) {
    let date = dateFormatter.string(from: response.date)
    let viewModel = CreateOrder.FormatExpirationDate.ViewModel(date: date)
    viewController?.displayExpirationDate(viewModel: viewModel)
  }
}
